language: java

script:
#  - ./gradlew build -PjunitVersion=5.0.0-M2 -PskipFindBugs
  - ./gradlew build
  - mvn test
  - ant test

jdk:
  - oraclejdk8
  - openjdk8

after_success:
  - ./gradlew jacocoTestReport coveralls

sudo: false
